create table employee (
    id bigint generated by default as identity,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    login_name varchar(255) not null,
    middle_name varchar(255),
    primary key (id)
);

insert into employee (id, first_name, last_name, login_name, middle_name)
values (1, "Maxim", "Abramkin", "Maksim.Abramkin", "Andreevich");