create table employee (id bigint generated by default as identity, first_name varchar(255) not null, last_name varchar(255) not null, login_name varchar(255) not null, middle_name varchar(255), primary key (id))
create table holiday_period (id bigint generated by default as identity, date_start timestamp, employee_id bigint, num_days bigint, primary key (id))
